# Generated by Django 5.1.4 on 2024-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_description_en_post_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='like',
        ),
    ]
